name: PHPUnit

on: pull_request

permissions:
  contents: read

concurrency:
  group: phpunit
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read

    outputs:
      src: ${{ steps.changes.outputs.src }}

    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        continue-on-error: true
        with:
          filters: |
            src:
              - '.github/workflows/**'
              - 'src/**'
              - 'tests/**'
              - 'vendor/**'
              - 'composer.json'
              - 'composer.lock'

  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [8.1, 8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php-versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@7bf05c6b704e0b9bfee22300130a31b5ea68d593 # v2.36.0
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json, openssl
          coverage: xdebug
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up dependencies
        run: composer i

      - name: PHPUnit
        run: composer run test:unit

  integration:
    runs-on: ubuntu-latest

    name: Integration

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up php
        uses: shivammathur/setup-php@7bf05c6b704e0b9bfee22300130a31b5ea68d593 # v2.36.0
        with:
          php-version: 8.4
          extensions: json, openssl, zip
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up dependencies
        run: composer i

      - name: PHPUnit
        run: composer run test:integration

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: [changes, phpunit, integration]

    if: always()

    name: phpunit-summary

    steps:
      - name: Summary status
        run: if ${{ needs.changes.outputs.src != 'false' && (needs.phpunit.result != 'success' || needs.integration.result != 'success') }}; then exit 1; fi
