name: Static analysis

on: pull_request

concurrency:
  group: psalm-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    name: static-psalm-analysis
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up php8.1
        uses: shivammathur/setup-php@c482204203a2eb89366ad513842766b70efaaee8 # v2.36.0
        with:
          php-version: 8.1
          extensions: json, openssl
          coverage: none
          ini-file: development
          # Temporary workaround for missing pcntl_* in PHP 8.3
          ini-values: disable_functions=
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer i

      - name: Run coding standards check
        run: composer run psalm -- --output-format=github
